export const SHOW_WALLET_MODAL = "SHOW_WALLET_MODAL";
export const HIDE_WALLET_MODAL = "HIDE_WALLET_MODAL";
export const SHOW_SIDEMENU = "SHOW_SIDEMENU";
export const HIDE_SIDEMENU = "HIDE_SIDEMENU";
export const SET_HEADER_HEIGHT = "SET_HEADER_HEIGHT";
export const SET_SIDEBAR_HEIGHT = "SET_SIDEBAR_HEIGHT";
export const SET_ACCOUNT = "SET_ACCOUNT";